module.exports = {
  SIGNAL: "SIGNAL_RECEIVED",

  TELEMETRY: "TELEMETRY_PROCESSED",

  INCIDENT: "INCIDENT_CREATED",

  ESCALATION: "ESCALATED",

  REPLAY: "REPLAY_GENERATED",

  EVIDENCE: "EVIDENCE_ATTACHED",

  ANALYTICS: "ANALYTICS_UPDATED",

  DASHBOARD: "DASHBOARD_UPDATED",

  HEALTHY: "HEALTHY",

  DEGRADED: "DEGRADED",

  FAILED: "FAILED"
};