const runtimeStatus = {
  SIGNAL_RECEIVED: "SIGNAL_RECEIVED",
  TELEMETRY_CREATED: "TELEMETRY_CREATED",
  INCIDENT_CREATED: "INCIDENT_CREATED",
  ESCALATION_CREATED: "ESCALATION_CREATED",
  REPLAY_READY: "REPLAY_READY",
  EVIDENCE_CREATED: "EVIDENCE_CREATED",
  COMPLETED: "COMPLETED"
};

module.exports = runtimeStatus;