module.exports = {

  SIGNAL: "SIGNAL",
  TELEMETRY: "TELEMETRY",
  INCIDENT: "INCIDENT",
  ESCALATION: "ESCALATION",
  REPLAY: "REPLAY",
  EVIDENCE: "EVIDENCE",
  ANALYTICS: "ANALYTICS",
  OBSERVABILITY: "OBSERVABILITY"

};